### ISSUE TITLE
manual/auto version bump PRs yield different in CI results

### ISSUE THREAD

**Issue by carlodri** [regro/cf-scripts#46] opened 2018-03-03 09:27 UTC
There are two PRs in this feedstock, one created manually by me, and the other was created by the autotick-bot:

https://github.com/conda-forge/menuinst-feedstock/pull/1

and

https://github.com/conda-forge/menuinst-feedstock/pull/2

The changeset is exactly the same, but the CI succeeds in the manual PR, but fails in the bot PR with this error

```bash
INFO:conda.gateways.disk.delete:rm_rf failed for c:\users\appveyor\appdata\local\temp\1\tmpl4pwk8
Traceback (most recent call last):
  File "C:\Miniconda-x64\Scripts\conda-build-script.py", line 5, in <module>
    sys.exit(conda_build.cli.main_build.main())
  File "C:\Miniconda-x64\lib\site-packages\conda_build\cli\main_build.py", line 342, in main
    execute(sys.argv[1:])
  File "C:\Miniconda-x64\lib\site-packages\conda_build\cli\main_build.py", line 333, in execute
    noverify=args.no_verify)
  File "C:\Miniconda-x64\lib\site-packages\conda_build\api.py", line 97, in build
    need_source_download=need_source_download, config=config)
  File "C:\Miniconda-x64\lib\site-packages\conda_build\build.py", line 1524, in build_tree
    config=config)
  File "C:\Miniconda-x64\lib\site-packages\conda_build\build.py", line 1159, in build
    built_package = bundlers[output_dict.get('type', 'conda')](output_dict, m, config, env)
  File "C:\Miniconda-x64\lib\site-packages\conda_build\build.py", line 939, in bundle_conda
    path_to_package=tmp_path)
  File "C:\Miniconda-x64\lib\site-packages\conda_verify\verify.py", line 30, in verify_package
    getattr(package_check, method)() is not None]
  File "C:\Miniconda-x64\lib\site-packages\conda_verify\checks.py", line 309, in check_windows_arch
    file_object_type = get_object_type(file_header)
  File "C:\Miniconda-x64\lib\site-packages\conda_verify\utilities.py", line 117, in get_object_type
    return "DLL " + DLL_TYPES.get(i)
TypeError: cannot concatenate 'str' and 'NoneType' objects
Command exited with code 1
```

Why is this happening? I imagine that build config is different for bot and manual, but probably there is something to be fixed here.

**Comment by CJ-Wright** [comment] 2018-03-03 16:23
The configurations should be the same, so I'm not certain what is going on here either.
I think this is the first error of this type for the bot, so some investigation is warranted.

**Comment by jakirkham** [comment] 2018-03-03 21:02
Yeah it looks like a [conda-verify]( https://github.com/conda/conda-verify ) issue. We should raise over there. That project is coming back online after being dormant for a while. So it's not surprising to see a few issues. They may have already fixed it, but it would be good to get confirmation. If it's not fixed, it would be good to get there attention about this issue at least.

**Comment by CJ-Wright** [comment] 2018-04-02 12:26
I'm going to close this as this isn't really a bot issue.

**Closed by CJ-Wright** 2018-04-02 12:26 UTC

**Comment by carlodri** [comment] 2018-04-09 06:48
@CJ-Wright I'm quite puzzled by this issue, it happened again here https://github.com/conda-forge/memory_profiler-feedstock/pull/12 (relevant CI [here](https://ci.appveyor.com/project/conda-forge/memory-profiler-feedstock/build/1.0.19/job/bp6dp0lyi7tqn0l7))

**Comment by jakirkham** [comment] 2018-04-09 07:05
So I’d drop a link to the log on that upstream `conda-verify` issue. This seems like what they were asking about recently (i.e. reproducible cases).
