### ISSUE TITLE
Missing CuPy updates

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#1345] opened 2021-01-29 17:48 UTC
We appear to be missing a CuPy 8.4.0 update PR. It was tagged and pushed to PyPI yesterday, but no PR appears to be added. We did this manually for now ( https://github.com/conda-forge/cupy-feedstock/pull/96 ), but it would be nice to understand and correct anything that caused the bot to miss this

cc @leofang

**Comment by leofang** [comment] 2021-01-29 17:50
Thanks John! Could it be blocked by the failing migrators?

**Comment by leofang** [comment] 2021-02-27 07:35
Just FYI, we also missed the CuPy 8.5.0 update released yesterday. I have two theories for the cause:
1. there are at least one or multiple migrators either pending or in the unsolvable/error state
2. we manually perform the CUDA-related migrators using `conda_build_config.yaml`

If No.2 is the cause it'd be a bummer.

**Comment by CJ-Wright** [comment] 2021-02-27 13:09
The bot doesn't handle git_rev sources and so cupy is out of the bot's scope as the code is currently.

**Comment by jakirkham** [comment] 2021-02-27 20:56
Yeah we had do that temporarily as there was a bug that was difficult to workaround without just having the source. We’ve since switched back to the `sdist` now that that bug is fixed

https://github.com/cupy/cupy/issues/4597

**Comment by beckermr** [comment] 2021-02-27 21:58
Ok. Let's keep watching.

**Comment by leofang** [comment] 2021-02-28 06:12
Well, my theories cannot be ruled out. At the time of releasing 8.4.0 (which was added manually because the bot didn't send one), it was still on the `sdist` source (https://github.com/conda-forge/cupy-feedstock/pull/96). We moved to the git source after that (https://github.com/conda-forge/cupy-feedstock/pull/100).

**Comment by beckermr** [comment] 2021-02-28 16:54
I added a test of the migrator on the feedstock here: https://github.com/regro/cf-scripts/pull/1369

I also added a feature where the bot will ship version PRs even if they don't rerender assuming that automerge and check_solvable are off.

**Comment by leofang** [comment] 2021-03-01 04:21
Thanks, @beckermr! So am I understanding it correctly that with #1369 you narrowed down the problem to either the solver or the smithy rerendering? 

On the new bot feature you added, does it mean it gives the maintainers a chance to take care rerendering by hand?

**Comment by leofang** [comment] 2021-03-01 04:22
> On the new bot feature you added, does it mean it gives the maintainers a chance to take care rerendering by hand?

Ah I found it, indeed it looks like so: #1371.

**Comment by jakirkham** [comment] 2021-03-25 04:07
Woot! We got an update PR ( https://github.com/conda-forge/cupy-feedstock/pull/113 ) 😄 🎉

**Comment by beckermr** [comment] 2021-03-25 10:35
great! I am closing this issue for now. feel free to reopen if you have more trouble.

**Closed by beckermr** 2021-03-25 10:35 UTC
