### ISSUE TITLE
regro-cf-autotick-bot does not update the sha256 checksum

### ISSUE THREAD

**Issue by tschoonj** [regro/cf-scripts#616] opened 2019-09-23 02:24 UTC
Noticed this for the second time in this PR: https://github.com/conda-forge/pyxrf-feedstock/pull/2

**Comment by isuruf** [comment] 2019-09-23 02:25
Duplicate of https://github.com/regro/cf-scripts/issues/529

**Closed by isuruf** 2019-09-23 02:25 UTC
