### ISSUE TITLE
conda-forge migrator triggering child build (postgis) before parent (gdal/libgdal) has migrate

### ISSUE THREAD

**Issue by xylar** [regro/cf-scripts#872] opened 2020-03-13 22:29 UTC
A conda-forge feedstock ([postgis](https://github.com/conda-forge/postgis-feedstock)) has a [pull request](https://github.com/conda-forge/postgis-feedstock/pull/40) for migration to `geos-3.8.1` even though one of its dependencies, `libgdal`, has not yet migrated.  The bot may be getting confused because there is an archived [libgdal-feedstock](https://github.com/conda-forge/libgdal-feedstock) but the current `libgdal` package is produced as part of the [gdal-feedstock](https://github.com/conda-forge/gdal-feedstock), which has (as of this writing) not yet migrated to `geos-3.8.1`: https://github.com/conda-forge/gdal-feedstock/pull/369

**Comment by xylar** [comment] 2020-03-13 22:30
@scopatz suggested I post this issue here.  It is based on a nearly identical issue posted here: https://github.com/conda-forge/conda-smithy/issues/1260

**Comment by beckermr** [comment] 2020-03-13 22:33
This was caused by a bug by me. You can add the bot rerun label or simply wait.

**Comment by xylar** [comment] 2020-03-13 22:38
Okay, but it also happened the last time we migrated `geos`.  Was the bug already there during that migration?

**Comment by beckermr** [comment] 2020-03-13 22:45
There has been more than one bug. Things are not always perfect.

**Comment by xylar** [comment] 2020-03-14 07:59
Yep, that happens.  The behavior seemed similar enough to the last migration that I figured it could be the same thing.

I asked the bot to rerun all the PRs that I noticed to be affected.  Let's see what happens.

**Comment by xylar** [comment] 2020-03-14 14:27
@beckermr, the `gdal` PR got merged but the bot doesn't seem to have re-created the PRs for the children yet.  How long would this be expected to take?

**Comment by beckermr** [comment] 2020-03-14 14:47
It could be a while. The bot has to harvest the JSON for ~2k PRs from the github API to check the status of these things. It can only do ~200 per hour right now and so it is pretty slow.

**Comment by xylar** [comment] 2020-03-14 15:14
Okay, no worries.  I just wondered if 16 hours was long enough that it might mean something had gone wrong.  Sounds like not.

**Comment by CJ-Wright** [comment] 2020-04-12 00:33
I think this has been fixed now in #954

**Closed by CJ-Wright** 2020-04-12 00:33 UTC
